version: "3.9"
services:
  api:
    build:
      dockerfile: "./Dockerfiles/Api_Dockerfile.yml"
    ports:
      - "60111:8031"
#    restart: always

  recomServise:
    build:
      dockerfile: "./Dockerfiles/RecomServise_Dockerfile.yml"
    ports:
      - "60112:8032"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "recomapi_as"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    build:
      context: './'
      dockerfile: "./Dockerfiles/Db_Dockerfile.yml"
    ports:
      - "60119:5432"